# Generated by Django 3.0.7 on 2020-09-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='QR Kod içeriği')),
                ('scale', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('color', models.CharField(choices=[('siyah', 'siyah'), ('kırmızı', 'kırmızı'), ('mavi', 'mavi'), ('yeşil', 'yeşil'), ('kahverengi', 'kahverengi'), ('mor', 'mor'), ('pembe', 'pembe'), ('sarı', 'sarı'), ('gri', 'gri'), ('açık mavi', 'açık mavi')], max_length=15)),
                ('background_color', models.CharField(choices=[('siyah', 'siyah'), ('kırmızı', 'kırmızı'), ('mavi', 'mavi'), ('yeşil', 'yeşil'), ('kahverengi', 'kahverengi'), ('mor', 'mor'), ('pembe', 'pembe'), ('sarı', 'sarı'), ('gri', 'gri'), ('açık mavi', 'açık mavi')], max_length=15)),
            ],
        ),
    ]
