# Generated by Django 3.0.7 on 2020-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='output_format',
            field=models.CharField(choices=[('SVG', 'SVG'), ('EPS', 'EPS'), ('PNG', 'PNG')], default='PNG', max_length=5, verbose_name='Çıktı Formatı'),
        ),
    ]
