# Generated by Django 3.0.7 on 2020-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0003_auto_20200913_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='output_format',
            field=models.CharField(choices=[('SVG', 'SVG'), ('EPS', 'EPS'), ('PNG', 'PNG')], default='PNG', max_length=5, verbose_name='Çıktı Formatı'),
        ),
    ]
