# Generated by Django 3.0.7 on 2020-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0004_qrcode_output_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='output_format',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='color',
            field=models.CharField(choices=[('black', 'siyah'), ('red', 'kırmızı'), ('blue', 'mavi'), ('green', 'yeşil'), ('brown', 'kahverengi'), ('purple', 'mor'), ('pink', 'pembe'), ('yellow', 'sarı'), ('grey', 'gri'), ('light_blue', 'açık mavi')], default='black', max_length=15),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='scale',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=5, max_length=2),
        ),
    ]
